org: slsplus
app: photo-album
stage: dev

component: cynosdb
name: photo-album-db

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:${app}-vpc.vpcId}
    subnetId: ${output:${stage}:${app}:${app}-vpc.subnetId}
  enablePublicAccess: true
